#!/usr/bin/env python3
"""
DBTT(C) Linear Modeling Pipeline (composition-focused)
------------------------------------------------------
Author: (generated by GPT-5 Pro)

What it does
------------
- Loads a CSV and models DBTT(C) from *composition-only* features, with optional
  inclusion of mechanical properties (hardness / tensile strength) if present enough.
- Handles per-row composition basis via an 'at/wt' column (auto/convert to wt% or at%).
- Balances composition to 100 by adjusting V to absorb any deficit/excess.
- Creates a synthetic AlloyID from composition to enable grouped CV.
- Detects outliers with LOF and runs the analysis *with and without* outliers.
- Produces a histogram of the percent non-null values across candidate features to
  help pick a missingness threshold.
- Saves metrics, coefficients, permutation importances, plots, and a cleaned snapshot.

Usage
-----
python dbtt_linear_regression.py --csv <path> \
    --target "DBTT(C)" \
    --out-dir dbtt_outputs \
    --basis-policy auto \
    --include-mech True \
    --mech-min-frac 0.60 \
    --feature-threshold 0.00 \
    --grouped-cv True \
    --n-splits 5 \
    --lof-contamination 0.10 \
    --random-state 42

Notes
-----
- We only use composition columns (element symbols like V, Cr, Ti, ...). All other
  non-composition columns are excluded *except* hardness / tensile strength, which
  can be optionally included if present enough.
- DBTT definition: assumed Charpy V-notch derived and comparable across rows.
- Grain size intentionally ignored per user guidance.
"""

import argparse
import math
import os
from pathlib import Path
from typing import List, Tuple, Dict

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import ElasticNetCV
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split, cross_validate, GroupKFold, KFold
from sklearn.neighbors import LocalOutlierFactor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.inspection import permutation_importance


# ---- Atomic weights for conversion (g/mol) ----
# Include a reasonably broad set typically seen in V alloys & impurities
ATOMIC_WEIGHTS: Dict[str, float] = {
    "H": 1.00794, "B": 10.811, "C": 12.0107, "N": 14.0067, "O": 15.9994,
    "Al": 26.9815386, "Si": 28.0855, "P": 30.973762, "S": 32.065,
    "Ti": 47.867, "V": 50.9415, "Cr": 51.9961, "Mn": 54.938045,
    "Fe": 55.845, "Co": 58.933195, "Ni": 58.6934, "Cu": 63.546,
    "Zr": 91.224, "Nb": 92.90638, "Mo": 95.96, "Ta": 180.94788,
    "W": 183.84, "Y": 88.90585, "La": 138.90547, "Ce": 140.116
}

# ---- Element symbol whitelist (exact column names) ----
ELEMENTS: List[str] = sorted(ATOMIC_WEIGHTS.keys())


def find_element_columns(df: pd.DataFrame) -> List[str]:
    """Return a list of columns that exactly match known element symbols."""
    candidates = [c for c in df.columns if c in ELEMENTS]
    return candidates


def find_mech_columns(df: pd.DataFrame) -> Tuple[List[str], List[str]]:
    """Detect likely hardness and tensile/strength columns."""
    cols_lower = {c: str(c).lower() for c in df.columns}
    hardness_cols = [c for c, lc in cols_lower.items()
                     if ("hardness" in lc) or ("vickers" in lc) or (lc.endswith("(hv)")) or (" hrc" in lc) or (lc == "hrc")]
    tensile_cols = [c for c, lc in cols_lower.items()
                    if ("tensile" in lc) or ("ultimate" in lc) or (" uts" in lc) or (lc.startswith("uts"))
                    or ("yield strength" in lc) or (" ys" in lc) or ("(mpa)" in lc and ("yield" in lc or "tensile" in lc or "ultimate" in lc))]
    return hardness_cols, tensile_cols


def percent_nonnull(series: pd.Series) -> float:
    return float(series.notna().mean() * 100.0)


def plot_nonnull_hist(nonnull_percents: pd.Series, out_path: Path, bins: int = 20) -> None:
    """Plot histogram of % non-null across columns."""
    plt.figure()
    plt.hist(nonnull_percents.values, bins=bins)
    plt.xlabel("% non-null across rows")
    plt.ylabel("Number of columns")
    plt.title("Distribution of % non-null values (candidate predictors)")
    plt.tight_layout()
    plt.savefig(out_path, dpi=150)
    plt.close()


def convert_row_basis_to_wt(row: pd.Series, comp_cols: List[str]) -> pd.Series:
    """Convert composition in at% to wt% for given row (in-place on a copy)."""
    at_fracs = np.array([row[c] if pd.notna(row[c]) else 0.0 for c in comp_cols], dtype=float)
    if at_fracs.sum() <= 0:
        return row
    masses = np.array([ATOMIC_WEIGHTS.get(c, np.nan) for c in comp_cols], dtype=float)
    if np.isnan(masses).any():
        # missing atomic weights; skip conversion
        return row
    # Convert atomic % to weight %
    # mass_i ∝ at_i * AW_i -> wt% = mass_i / sum(mass_i) * 100
    mass_i = at_fracs * masses
    total_mass = mass_i.sum()
    if total_mass > 0:
        wt = mass_i / total_mass * 100.0
        for i, c in enumerate(comp_cols):
            row[c] = wt[i]
    return row


def convert_row_basis_to_at(row: pd.Series, comp_cols: List[str]) -> pd.Series:
    """Convert composition in wt% to at% for given row (in-place on a copy)."""
    wt_fracs = np.array([row[c] if pd.notna(row[c]) else 0.0 for c in comp_cols], dtype=float)
    if wt_fracs.sum() <= 0:
        return row
    masses = np.array([ATOMIC_WEIGHTS.get(c, np.nan) for c in comp_cols], dtype=float)
    if np.isnan(masses).any():
        # missing atomic weights; skip conversion
        return row
    # Convert weight % to atomic %
    # m_i = wt_i; n_i ∝ m_i / AW_i -> at% = n_i / sum(n_i) * 100
    n_i = wt_fracs / masses
    total_n = n_i.sum()
    if total_n > 0:
        at = n_i / total_n * 100.0
        for i, c in enumerate(comp_cols):
            row[c] = at[i]
    return row


def maybe_convert_basis(df: pd.DataFrame, comp_cols: List[str], atwt_col: str, policy: str) -> pd.DataFrame:
    """
    Convert rows to a common basis according to policy:
      - 'auto': leave as-is (assumes data are already coherent per row)
      - 'wt': convert rows where atwt_col == 'at' to wt%
      - 'at': convert rows where atwt_col == 'wt' to at%
    """
    if policy not in {"auto", "wt", "at"}:
        raise ValueError("basis-policy must be one of: auto, wt, at")
    if policy == "auto":
        return df

    df = df.copy()
    # Find the indicator column (case-insensitive exact match for 'at/wt')
    atwt_candidates = [c for c in df.columns if str(c).strip().lower() in {"at/wt", "atwt", "basis"}]
    if not atwt_candidates:
        # No guidance column; assume already coherent
        return df
    atwt = atwt_candidates[0]

    if policy == "wt":
        mask = df[atwt].astype(str).str.lower().str.contains("at")
        df.loc[mask, :] = df.loc[mask, :].apply(lambda row: convert_row_basis_to_wt(row, comp_cols), axis=1)
    elif policy == "at":
        mask = df[atwt].astype(str).str.lower().str.contains("wt")
        df.loc[mask, :] = df.loc[mask, :].apply(lambda row: convert_row_basis_to_at(row, comp_cols), axis=1)
    return df


def balance_to_100(df: pd.DataFrame, comp_cols: List[str], adjust_element: str = "V") -> pd.DataFrame:
    """
    Ensure composition sums to exactly 100 per row by adjusting 'adjust_element'.
    If the adjust_element is missing, it will be created. If adjustment would make
    it negative, values are clipped to a tiny positive number and remaining elements
    are renormalized to sum to 100.
    """
    df = df.copy()
    if adjust_element not in df.columns:
        df[adjust_element] = 0.0

    sums = df[comp_cols].sum(axis=1, skipna=True)
    delta = 100.0 - sums

    # Add delta to adjust element
    df[adjust_element] = df[adjust_element].fillna(0.0) + delta

    # If any negatives, renormalize the row to non-negative values summing to 100
    def _fix_row(row):
        comps = row[comp_cols].fillna(0.0).astype(float)
        comps[comps < 0] = 0.0
        s = comps.sum()
        if s > 0:
            row[comp_cols] = comps / s * 100.0
        return row

    any_negative = (df[comp_cols] < 0).any(axis=1)
    if any_negative.any():
        df.loc[any_negative, :] = df.loc[any_negative, :].apply(_fix_row, axis=1)

    return df


def make_alloy_id(df: pd.DataFrame, comp_cols: List[str], decimals: int = 3) -> pd.Series:
    """
    Create a deterministic composition fingerprint string, e.g. "Cr:12.5|Ti:4.0|V:83.5".
    Elements with ~0 are omitted.
    """
    def _fmt(v):
        if pd.isna(v) or abs(v) < 1e-12:
            return None
        return round(float(v), decimals)

    ids = []
    for _, row in df[comp_cols].iterrows():
        parts = []
        for el in sorted(comp_cols):
            val = _fmt(row[el])
            if val is not None and val != 0:
                parts.append(f"{el}:{val}")
        ids.append("|".join(parts))
    return pd.Series(ids, index=df.index, name="AlloyID")


def select_features(df: pd.DataFrame,
                    include_mech: bool,
                    mech_min_frac: float,
                    feature_threshold: float) -> Tuple[pd.DataFrame, List[str], List[str]]:
    """
    Keep only composition columns, and optionally add mechanical columns if
    present in at least mech_min_frac of rows. Then drop any columns with
    non-null fraction below feature_threshold.
    """
    comp_cols = find_element_columns(df)

    # Candidate mechanical properties
    hardness_cols, tensile_cols = find_mech_columns(df)
    mech_cols = []
    if include_mech:
        for c in hardness_cols + tensile_cols:
            if percent_nonnull(df[c]) / 100.0 >= mech_min_frac:
                mech_cols.append(c)

    # Form the candidate feature set and apply feature_threshold
    candidate_cols = comp_cols + mech_cols
    keep_cols = []
    for c in candidate_cols:
        if percent_nonnull(df[c]) >= feature_threshold * 100.0:
            keep_cols.append(c)

    # Return the filtered dataframe and the lists for reporting
    return df[keep_cols].copy(), comp_cols, mech_cols


def build_preprocessor(numeric_cols: List[str]) -> ColumnTransformer:
    num_pipe = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ])
    # Only numeric features remain; no categoricals
    return ColumnTransformer([("num", num_pipe, numeric_cols)], remainder="drop")


def train_and_report(X: pd.DataFrame, y: np.ndarray, groups: pd.Series,
                     out_prefix: Path, random_state: int, n_splits: int) -> Dict[str, float]:
    """
    Fit ElasticNetCV with cross-validation, evaluate on a held-out split,
    compute permutation importances, and save artifacts.
    """
    # Train/test split (stratification not applicable for regression)
    X_train, X_test, y_train, y_test, g_train, g_test = train_test_split(
        X, y, groups, test_size=0.2, random_state=random_state
    )

    numeric_cols = X.columns.tolist()
    preproc = build_preprocessor(numeric_cols)

    model = ElasticNetCV(
        l1_ratio=[0.1, 0.3, 0.5, 0.7, 0.9, 1.0],
        cv=5,
        random_state=random_state,
        max_iter=10000
    )

    pipe = Pipeline([("prep", preproc), ("model", model)])

    # Cross-validate on training split with grouped CV if possible
    if groups is not None and len(set(g_train)) >= n_splits:
        cv = GroupKFold(n_splits=n_splits)
        cv_results = cross_validate(
            pipe, X_train, y_train,
            cv=cv.split(X_train, y_train, groups=g_train),
            scoring=["r2", "neg_mean_absolute_error"]
        )
    else:
        cv = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
        cv_results = cross_validate(
            pipe, X_train, y_train,
            cv=cv,
            scoring=["r2", "neg_mean_absolute_error"]
        )

    # Fit on training split and evaluate on holdout
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)

    pi = permutation_importance(
            pipe, X_test, y_test,
            n_repeats=30, random_state=random_state, scoring='r2'
            )
    pi_names = list(X_test.columns)
    assert len(pi_names) == pi.importances_mean.shape[0], (len(pi_names), pi.importances_mean.shape[0])

    pi_df = pd.DataFrame({
        "feature": pi_names,
        "importance_mean": pi.importances_mean,
        "importance_std": pi.importances_std,
        }).sort_values("importance_mean", ascending=False)
    pi_df.to_csv(out_prefix.with_suffix(".perm_importance.csv"), index=False)

    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)

    # Save metrics
    metrics = {
        "r2_cv_mean": float(np.mean(cv_results["test_r2"])),
        "r2_cv_std": float(np.std(cv_results["test_r2"])),
        "mae_cv_mean": float(np.mean(-cv_results["test_neg_mean_absolute_error"])),
        "mae_cv_std": float(np.std(cv_results["test_neg_mean_absolute_error"])),
        "r2_test": float(r2),
        "mae_test": float(mae)
    }
    pd.Series(metrics).to_json(out_prefix.with_suffix(".metrics.json"), indent=2)

    # Coefficients
    # After fit, we can derive feature names as transformed by the preprocessor
    prep = pipe.named_steps["prep"]
    try:
        feat_names = list(prep.get_feature_names_out())
        # Convert "num__<name>" back to original names for readability
        feat_names = [n.replace("num__", "") for n in feat_names]
    except Exception:
        feat_names = numeric_cols

    coefs = pipe.named_steps["model"].coef_
    coef_df = pd.DataFrame({"feature": feat_names, "coefficient": coefs})
    coef_df["abs_coefficient"] = coef_df["coefficient"].abs()
    coef_df.sort_values("abs_coefficient", ascending=False, inplace=True)
    coef_df.to_csv(out_prefix.with_suffix(".coefficients.csv"), index=False)

    # Permutation importance (held-out test)
    pi = permutation_importance(
        pipe, X_test, y_test, n_repeats=30, random_state=random_state, scoring="r2"
    )
    pi_df = pd.DataFrame({
        "feature": feat_names,
        "importance_mean": pi.importances_mean,
        "importance_std": pi.importances_std
    }).sort_values("importance_mean", ascending=False)
    pi_df.to_csv(out_prefix.with_suffix(".perm_importance.csv"), index=False)

    # Parity plot
    plt.figure()
    plt.scatter(y_test, y_pred, s=24)
    plt.xlabel("Actual DBTT(C)")
    plt.ylabel("Predicted DBTT(C)")
    plt.title("Parity plot (holdout)")
    lims = [min(np.min(y_test), np.min(y_pred)), max(np.max(y_test), np.max(y_pred))]
    plt.plot(lims, lims)
    plt.tight_layout()
    plt.savefig(out_prefix.with_suffix(".parity.png"), dpi=150)
    plt.close()

    return metrics


def run(args):
    out_dir = Path(args.out_dir)
    plots_dir = out_dir / "plots"
    out_dir.mkdir(parents=True, exist_ok=True)
    plots_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(args.csv)

    # Identify target
    target = args.target
    if target is None:
        candidates = [c for c in df.columns if "dbtt" in str(c).lower()]
        if not candidates:
            raise SystemExit("No --target provided and no column containing 'dbtt' found.")
        target = candidates[0]

    # Keep a copy of DBTT and drop rows with missing target
    y = pd.to_numeric(df[target], errors="coerce")
    keep = y.notna()
    df = df.loc[keep].copy()
    y = y.loc[keep].values

    # Select features per user guidance
    #  - composition columns only, optional mech (hardness/tensile) if present enough
    X_all, comp_cols_full, mech_cols_all = select_features(
        df, include_mech=args.include_mech, mech_min_frac=args.mech_min_frac,
        feature_threshold=args.feature_threshold
    )

    # Report non-null % histogram across candidate predictors
    nonnull_perc = X_all.apply(percent_nonnull, axis=0)
    nonnull_perc.sort_values(ascending=False).to_csv(out_dir / "nonnull_percent_by_column.csv", header=["percent_nonnull"])
    plot_nonnull_hist(nonnull_perc, plots_dir / "nonnull_percent_hist.png")

    # Optionally convert basis across rows
    X_all = maybe_convert_basis(pd.concat([X_all, df[[target]]], axis=1),  # pass target for safe copy alignment
                                comp_cols=[c for c in X_all.columns if c in ELEMENTS],
                                atwt_col="at/wt",
                                policy=args.basis_policy).drop(columns=[target])

    # Balance composition to 100 by adjusting V
    comp_cols = [c for c in X_all.columns if c in ELEMENTS]
    X_all = balance_to_100(pd.concat([X_all, df[[target]]], axis=1),
                           comp_cols=comp_cols, adjust_element="V").drop(columns=[target])

    # Create AlloyID for grouping (based on *composition only*)
    alloy_id = make_alloy_id(X_all, comp_cols=comp_cols, decimals=3)
    alloy_id.to_csv(out_dir / "alloy_id.csv", index=False)

    # --- BEFORE LOF ---
    # 1) Drop columns that are entirely NaN (prevents later shape mismatches)
    all_nan_cols = [c for c in X_all.columns if X_all[c].isna().all()]
    if all_nan_cols:
        print(f"Dropping all-NaN feature(s): {all_nan_cols}")
        X_all = X_all.drop(columns=all_nan_cols)

    # 2) LOF must not see NaNs → median impute specifically for LOF input
    from sklearn.impute import SimpleImputer
    imputer_lof = SimpleImputer(strategy="median")
    X_lof = imputer_lof.fit_transform(X_all.values)  # numpy array, no NaNs
    lof = LocalOutlierFactor(
            n_neighbors=args.n_splits if hasattr(args, "n_splits") else 15,
            contamination=args.lof_contamination if hasattr(args, "lof_contamination") else 0.10
            )
    lof_labels = lof.fit_predict(X_lof)  # -1 outlier, 1 inlier
    is_outlier = pd.Series(lof_labels == -1, index=X_all.index, name="is_outlier")
    is_outlier.to_csv(out_dir / "lof_outliers.csv", index=False)

    # Save a cleaned snapshot used for modeling
    cleaned = pd.concat([X_all, pd.Series(y, index=X_all.index, name=target), alloy_id, is_outlier], axis=1)
    cleaned.to_csv(out_dir / "cleaned_snapshot.csv", index=False)

    # Model: include outliers
    metrics_inc = train_and_report(
        X=X_all, y=y, groups=alloy_id if args.grouped_cv else None,
        out_prefix=out_dir / "with_outliers",
        random_state=args.random_state, n_splits=args.n_splits
    )

    # Model: exclude outliers
    mask_inliers = ~is_outlier.values
    if mask_inliers.sum() >= max(10, args.n_splits):
        metrics_exc = train_and_report(
            X=X_all.loc[mask_inliers], y=y[mask_inliers], groups=alloy_id.loc[mask_inliers] if args.grouped_cv else None,
            out_prefix=out_dir / "without_outliers",
            random_state=args.random_state, n_splits=args.n_splits
        )
    else:
        metrics_exc = {"note": "Too few inliers to run outlier-excluded model."}

    # Write a human-readable summary
    with open(out_dir / "summary.txt", "w") as f:
        f.write("DBTT(C) Linear Modeling Pipeline (composition-focused)\n")
        f.write(f"Target: {target}\n")
        f.write(f"Rows: {len(df)} | Features (candidate): {X_all.shape[1]}\n")
        f.write(f"Composition columns used: {', '.join(comp_cols)}\n")
        if args.include_mech and len([c for c in X_all.columns if c not in comp_cols]) > 0:
            f.write("Mechanical columns included: " + ", ".join([c for c in X_all.columns if c not in comp_cols]) + "\n")
        f.write(f"\nNon-null histogram saved to: {plots_dir / 'nonnull_percent_hist.png'}\n")
        f.write("\nWITH outliers metrics:\n")
        for k, v in metrics_inc.items():
            f.write(f"  {k}: {v}\n")
        f.write("\nWITHOUT outliers metrics:\n")
        for k, v in metrics_exc.items():
            f.write(f"  {k}: {v}\n")

    print("Done. Outputs written to:", out_dir)


def parse_args():
    p = argparse.ArgumentParser(description="DBTT(C) linear modeling with composition-only predictors.")
    p.add_argument("--csv", required=True, help="Path to CSV file")
    p.add_argument("--target", default=None, help="Target column name (default: first column containing 'dbtt')")
    p.add_argument("--out-dir", default="dbtt_outputs", help="Output directory for artifacts")
    p.add_argument("--basis-policy", choices=["auto", "wt", "at"], default="auto",
                   help="Convert all rows to this basis using 'at/wt' indicator; 'auto' keeps per-row basis")
    p.add_argument("--include-mech", type=lambda x: str(x).lower() in {"1","true","t","yes","y"}, default=True,
                   help="Optionally include hardness/strength if present enough")
    p.add_argument("--mech-min-frac", type=float, default=0.60, help="Min non-null fraction to include mech columns")
    p.add_argument("--feature-threshold", type=float, default=0.00,
                   help="Drop candidate predictors with non-null fraction below this threshold (0–1).")
    p.add_argument("--grouped-cv", type=lambda x: str(x).lower() in {"1","true","t","yes","y"}, default=True,
                   help="Use synthetic AlloyID for grouped CV to avoid leakage across near-duplicate compositions.")
    p.add_argument("--n-splits", type=int, default=5, help="Number of CV folds.")
    p.add_argument("--lof-contamination", type=float, default=0.10, help="LOF contamination fraction (0–0.5).")
    p.add_argument("--random-state", type=int, default=42, help="Random seed.")
    return p.parse_args()


if __name__ == "__main__":
    run(parse_args())
